from .Menambah_Laporan import Menambah_Laporan
from .Menampilkan_Daftar_Laporan import Menampilkan_Daftar_Laporan
from .Menghapus_Laporan import Menghapus_Laporan
from .Mengupdate_Laporan import Mengupdate_Laporan